version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/src
    depends_on:
      - db

  db:
    image: sqlite3
    volumes:
      - db_data:/mydb.sqlite

volumes:
  db_data:
